"""Separate Section 9 predicates using triangle BFS and open-cell atom sets.

Does not import, read, or call the main region/predicate functions. Shared inputs are
alpha, sigma, edge-mask conventions, and paper definitions. Host legality and
generation completeness are checked elsewhere; this checks nonempty purely bad sets.

alpha is a fixed-point-free involution; sigma cycles are vertices;
phi=sigma o alpha cycles are faces. Edges follow min(d, alpha[d]); bits encode atoms.
Direct execution tests two independently constructed hosts, not all candidates.
"""

from functools import lru_cache
from itertools import combinations
from typing import NamedTuple
import json


def _cycles(permutation):
    """Separate permutation decomposition; start at the least unvisited dart."""
    n = len(permutation)
    if sorted(permutation) != list(range(n)):
        raise ValueError("Input is not a permutation of 0..n-1")
    visited = set()
    answer = []
    for start in range(n):
        if start in visited:
            continue
        cycle = []
        here = start
        while here not in visited:
            visited.add(here)
            cycle.append(here)
            here = permutation[here]
        if here != start:
            raise ValueError("Permutation cycle does not return to its start")
        answer.append(tuple(cycle))
    return tuple(answer)


def _count_bits(value):
    return bin(value).count("1")


class _Region(NamedTuple):
    triangles: int
    edges: int
    vertices: int
    boundary: int
    atoms: int


class _Host:
    def __init__(self, alpha, sigma):
        n = len(alpha)
        if len(sigma) != n or not n:
            raise ValueError("Host dart counts disagree")
        _cycles(alpha)
        if any(alpha[d] == d or alpha[alpha[d]] != d for d in range(n)):
            raise ValueError("alpha is not a fixed-point-free involution")
        vertices = _cycles(sigma)
        faces = _cycles(tuple(sigma[alpha[d]] for d in range(n)))
        representatives = tuple(d for d in range(n) if d < alpha[d])
        if len(vertices) != 6 or len(representatives) != 12 or len(faces) != 8:
            raise ValueError("A spherical triangular host with 6 vertices, 12 edges, and 8 faces is required")
        if any(len(face) != 3 for face in faces):
            raise ValueError("Host is not a triangular cell decomposition")
        # Check the orbit generated by alpha and sigma to exclude disconnected inputs.
        found = {0}
        queue = [0]
        while queue:
            d = queue.pop()
            for neighbor in (alpha[d], sigma[d]):
                if neighbor not in found:
                    found.add(neighbor)
                    queue.append(neighbor)
        if len(found) != n:
            raise ValueError("Host is disconnected")

        vertex_of = [None] * n
        face_of = [None] * n
        for v, cycle in enumerate(vertices):
            for d in cycle:
                vertex_of[d] = v
        for f, cycle in enumerate(faces):
            for d in cycle:
                face_of[d] = f
        self.edge_vertices = tuple(
            (vertex_of[d], vertex_of[alpha[d]]) for d in representatives
        )
        self.edge_faces = tuple(
            (face_of[d], face_of[alpha[d]]) for d in representatives
        )
        self.vertex_faces = tuple(
            frozenset(face_of[d] for d in cycle) for cycle in vertices
        )
        self.edge_count = len(representatives)
        self.face_count = len(faces)
        self.vertex_count = len(vertices)
        self.all_edges = (1 << self.edge_count) - 1

    def regions(self, retained):
        """BFS across deleted edges in the dual graph; regions need not be discs."""
        adjacency = [set() for _ in range(self.face_count)]
        used_vertices = 0
        for edge, (left, right) in enumerate(self.edge_faces):
            if retained & (1 << edge):
                a, b = self.edge_vertices[edge]
                used_vertices |= (1 << a) | (1 << b)
            else:
                adjacency[left].add(right)
                adjacency[right].add(left)

        component_of = [-1] * self.face_count
        triangle_sets = []
        for start in range(self.face_count):
            if component_of[start] != -1:
                continue
            index = len(triangle_sets)
            component_of[start] = index
            queue = [start]
            triangles = 0
            while queue:
                face = queue.pop()
                triangles |= 1 << face
                for neighbor in adjacency[face]:
                    if component_of[neighbor] == -1:
                        component_of[neighbor] = index
                        queue.append(neighbor)
            triangle_sets.append(triangles)

        edge_sets = [0] * len(triangle_sets)
        vertex_sets = [0] * len(triangle_sets)
        boundary_sets = [0] * len(triangle_sets)
        for edge, (left, right) in enumerate(self.edge_faces):
            if retained & (1 << edge):
                a, b = self.edge_vertices[edge]
                boundary_sets[component_of[left]] |= (1 << a) | (1 << b)
                boundary_sets[component_of[right]] |= (1 << a) | (1 << b)
            else:
                if component_of[left] != component_of[right]:
                    raise AssertionError("Deleted edge fails to connect its two incident faces")
                edge_sets[component_of[left]] |= 1 << edge
        for vertex, incident_faces in enumerate(self.vertex_faces):
            if used_vertices & (1 << vertex):
                continue
            components = {component_of[face] for face in incident_faces}
            if len(components) != 1:
                raise AssertionError("Neighborhood of an unused mark was incorrectly split")
            vertex_sets[components.pop()] |= 1 << vertex

        return tuple(
            _Region(
                triangles, edges, vertices, boundary,
                triangles | (edges << self.face_count)
                | (vertices << (self.face_count + self.edge_count)),
            )
            for triangles, edges, vertices, boundary in zip(
                triangle_sets, edge_sets, vertex_sets, boundary_sets
            )
        )


@lru_cache(maxsize=64)
def _host(alpha, sigma):
    return _Host(alpha, sigma)


def check(alpha, sigma, mask):
    """Check one nonempty purely bad system from definitions; return booleans and counts.

    Do not filter by V or use the tested conclusions to infer free, clean, k, or good.
    Caller verifies essential and non-isotopic host arcs; reject non-purely-bad inputs.
    """
    host = _host(tuple(alpha), tuple(sigma))
    if not isinstance(mask, int) or mask <= 0 or mask & ~host.all_edges:
        raise ValueError("mask must specify a valid nonempty edge subset")
    objects = []
    endpoint_groups = {}
    used = 0
    for edge, (a, b) in enumerate(host.edge_vertices):
        bit = 1 << edge
        if not (mask & bit):
            continue
        used |= (1 << a) | (1 << b)
        if a == b:
            objects.append(bit)
        else:
            pair = tuple(sorted((a, b)))
            endpoint_groups[pair] = endpoint_groups.get(pair, 0) | bit
    if any(_count_bits(group) < 2 for group in endpoint_groups.values()):
        raise ValueError("Input contains a non-loop arc without an endpoint-pair partner")
    objects.extend(endpoint_groups.values())
    forbidden_pairs = set(endpoint_groups)  # The paper's F; single endpoints of loops are excluded.
    face_atoms = {region.atoms for region in host.regions(mask)}

    free = []
    for owner, own_edges in enumerate(objects):
        for region in host.regions(own_edges):
            # Objects share no edges. All open edges of another object lie in a gap
            # exactly when that object lies in the gap closure; edge closures contain endpoints.
            contained_other = any(
                other != owner and (edges & region.edges) == edges
                for other, edges in enumerate(objects)
            )
            if not contained_other:
                free.append(region)

    is_face = tuple(region.atoms in face_atoms for region in free)
    is_clean = []
    for region in free:
        boundary_vertices = [
            vertex for vertex in range(host.vertex_count)
            if region.boundary & (1 << vertex)
        ]
        is_clean.append(all(
            (a, b) in forbidden_pairs
            for a, b in combinations(boundary_vertices, 2)
        ))
    free_k = tuple(_count_bits(region.vertices) for region in free)
    two_disjoint = any(
        (left.atoms & right.atoms) == 0 for left, right in combinations(free, 2)
    )
    all_faces = all(is_face)
    good_atoms = {
        region.atoms
        for region, face, clean, k in zip(free, is_face, is_clean, free_k)
        if face and clean and k in (1, 2)
    }
    return {
        "9.11": two_disjoint and all_faces,
        "9.14": all(k >= 1 for k in free_k),
        "9.15": bool(good_atoms),
        "9.16": _count_bits(used) <= 4,
        "free_count": len(free),
        "good_count": len(good_atoms),
        "V": _count_bits(used),
        "9.11_disjoint": two_disjoint,
        "9.11_faces": all_faces,
        "9.13": all(is_clean),
        "free_k": free_k,
    }


def _demonstration_host(split_sides):
    """Build a double self-folded sphere and subdivide faces without other generators."""
    # Darts 0/1 form a loop; 2/3 and 4/5 are radii to interior marks on its two sides.
    alpha = [1, 0, 3, 2, 5, 4]
    faces = [[0, 2, 3], [1, 4, 5]]
    for index in split_sides:
        a, b, c = faces.pop(index)
        u, ur, v, vr, w, wr = range(len(alpha), len(alpha) + 6)
        alpha.extend([ur, u, vr, v, wr, w])
        faces.extend([[a, u, wr], [b, v, ur], [c, w, vr]])
    phi = [0] * len(alpha)
    for face in faces:
        for d, after in zip(face, face[1:] + face[:1]):
            phi[d] = after
    sigma = [phi[alpha[d]] for d in range(len(alpha))]
    return alpha, sigma


def _self_test():
    results = []
    # Subdivide one side repeatedly, leaving 4 and 1 interior marks across the loop.
    alpha, sigma = _demonstration_host([0, 1, 3])
    result = check(alpha, sigma, 1)
    assert result["free_count"] == 2 and result["good_count"] == 1
    assert sorted(result["free_k"]) == [1, 4] and result["V"] == 1
    assert all(result[key] for key in ("9.11", "9.13", "9.14", "9.15", "9.16"))
    results.append(result)
    # Subdivide both sides, leaving 3 and 2 interior marks across the loop.
    alpha, sigma = _demonstration_host([0, 0, 0])
    result = check(alpha, sigma, 1)
    assert result["free_count"] == 2 and result["good_count"] == 1
    assert sorted(result["free_k"]) == [2, 3] and result["V"] == 1
    assert all(result[key] for key in ("9.11", "9.13", "9.14", "9.15", "9.16"))
    results.append(result)
    print(json.dumps({"independent_self_test": "passed", "results": results}, ensure_ascii=False))


if __name__ == "__main__":
    _self_test()
